name: library/grafana:10.2

on:
  schedule:
  - cron: '0 0 * * *' # Everyday at 12AM

  push:
    branches: [main]
    paths:
    - 'library/grafana/10.2/**'
    - '.github/workflows/library-grafana10.2.yaml'
    - '!library/grafana/10.2/README.md'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
    - 'library/grafana/10.2/**'
    - '.github/workflows/library-grafana10.2.yaml'
    - '!library/grafana/10.2/README.md'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - plat: qemu
          arch: x86_64
        - plat: fc
          arch: x86_64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build grafana10.2
      uses: unikraft/kraftkit@staging
      with:
        loglevel: debug
        workdir: library/grafana/10.2
        runtimedir: /github/workspace/.kraftkit
        plat: ${{ matrix.plat }}
        arch: ${{ matrix.arch }}
        push: false
        output: oci://index.unikraft.io/unikraft.org/grafana:10.2

    - name: Archive OCI digests
      uses: actions/upload-artifact@v4
      with:
        name: oci-digests-${{ matrix.arch }}-${{ matrix.plat }}
        path: ${{ github.workspace }}/.kraftkit/oci/digests
        if-no-files-found: error

  push:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to OCI registry
      uses: docker/login-action@v3
      with:
        registry: index.unikraft.io
        username: ${{ secrets.REG_USERNAME }}
        password: ${{ secrets.REG_TOKEN }}

    - name: Retrieve, merge and push OCI digests
      uses: ./.github/actions/merge-oci-digests
      with:
        name: index.unikraft.io/unikraft.org/grafana:10.2
        push: true


  run-remote:
    name: Test grafana 1.1 (Remote OCI)
    needs: [build, push]
    runs-on: ubuntu-latest

    steps:
      - name: Login to OCI registry
        uses: docker/login-action@v3
        with:
          registry: index.unikraft.io
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Pull, run, validate and cleanup remote container
        run: |
          set -euo pipefail
          IMAGE=index.unikraft.io/unikraft.org/grafana:10.2
          echo "Pulling remote OCI image..."
          docker pull "$IMAGE"
          echo "Starting remote unikernel container..."
          CONTAINER_ID=$(docker run --rm -d -p 3000:3000 "$IMAGE")
          echo "Waiting for port 3000"
          TIMEOUT=10
          START_TS=$(date +%s)
          until nc -z localhost 3000; do
            if [ $(( $(date +%s) - START_TS )) -ge $TIMEOUT ]; then
              echo "ERROR: port 3000 did not open within ${TIMEOUT}s" >&2
              docker logs "$CONTAINER_ID" >&2 || true
              docker stop "$CONTAINER_ID" || true
              exit 1
            fi
            sleep 1
          done
          echo "Port 3000 is now accepting connections"
          echo "Validating HTTP response"
          EXPECTED="Hello, World!"
          RESPONSE=$(curl -fs http://localhost:3000/)
          if [ "$RESPONSE" != "$EXPECTED" ]; then
            echo "ERROR: expected '$EXPECTED' but got '$RESPONSE'" >&2
            docker logs "$CONTAINER_ID" >&2 || true
            docker stop "$CONTAINER_ID" || true
            exit 1
          fi
          echo "Response is correct: '$RESPONSE'"
          echo "Stopping container"
          docker stop "$CONTAINER_ID" || true
  run-local:
    name: Test grafana:10.2 (Local build)
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install kraft CLI
        run: |
          echo "deb [trusted=yes] https://deb.pkg.kraftkit.sh/ /" | sudo tee /etc/apt/sources.list.d/kraftkit.list
          sudo apt-get update
          sudo apt-get install -y kraftkit
      - name: Build, run, validate and cleanup local unikernel
        run: |
          set -euo pipefail
          sudo chmod 666 /dev/kvm
          cd library/grafana/10.2
      
          echo "Build unikernel locally"
          kraft build --no-cache --no-update --plat qemu --arch x86_64

          echo "Run local unikernel"
          kraft run --rm -M 256M -p 3000:3000 --plat qemu --arch x86_64 . &
          PID=$!
          sleep 5

          echo "Wait for port 3000"
          TIMEOUT=10
          START_TS=$(date +%s)
          until nc -z localhost 8080; do
            if [ $(( $(date +%s) - START_TS )) -ge $TIMEOUT ]; then
              echo "ERROR: port 3000 did not open within ${TIMEOUT}s" >&2
              sudo kill "$PID" || true
              exit 1
            fi
            sleep 1
          done
          echo "Port 3000 is now accepting connections"

          echo "Validate HTTP response"
          EXPECTED="Hello, World!"
          RESPONSE=$(curl -fs http://localhost:3000/)
          if [ "$RESPONSE" != "$EXPECTED" ]; then
            echo "ERROR: expected '$EXPECTED' but got '$RESPONSE'" >&2
            sudo kill "$PID" || true
            exit 1
          fi
          echo "Response is correct: '$RESPONSE'"
      
          echo "Cleanup unikernel"
          sudo kill "$PID" || true